FROM ubuntu:14.04

RUN apt-get update && apt-get install -q -y axel xorg unzip

RUN axel http://cdn.astah.net/downloads/astah-community-7_0_0-846701.zip
RUN unzip astah-community-7_0_0-846701.zip

CMD 
